<?php
/**
 *
 * Generated by StarterBuilder
 */
class teste extends TPage
{
    protected $form; // form
    protected $form_title; // form_title
    private $html;

    /**
     * Class constructor
     * Creates the page and the registration form
     */
    function __construct($param)
    {
        parent::__construct();

        $this->html = new THtmlRenderer('<style type="text/css">
	* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin:0;background-image:none;background-repeat:repeat;background-position:left top;background-attachment:scroll;background-size:auto;}.navbar-items-c{display:inline-block;float:right;}.navbar{background-color:#222;color:#ddd;min-height:50px;width:100%;}.navbar-container{max-width:950px;margin:0 auto;width:95%;}.navbar-container::after{content:"";clear:both;display:block;}.navbar-brand{vertical-align:top;display:inline-block;padding:5px;min-height:50px;min-width:50px;color:inherit;text-decoration:none;}.navbar-menu{padding:10px 0;display:block;float:right;margin:0;}.navbar-menu-link{margin:0;color:inherit;text-decoration:none;display:inline-block;padding:10px 15px;}.navbar-burger{margin:10px 0;width:45px;padding:5px 10px;display:none;float:right;cursor:pointer;}.navbar-burger-line{padding:1px;background-color:white;margin:5px 0;}@media fadeEffect{from{opacity:0;}to{opacity:1;}}@media (max-width: 768px){.navbar-burger{display:block;}.navbar-items-c{display:none;width:100%;}.navbar-menu{width:100%;}.navbar-menu-link{display:block;}}
</style>
<div data-gjs="navbar" class="navbar"><div class="navbar-container"><a href="/" class="navbar-brand"></a><div id="irmv" class="navbar-burger"><div class="navbar-burger-line"></div><div class="navbar-burger-line"></div><div class="navbar-burger-line"></div></div><div data-gjs="navbar-items" class="navbar-items-c"><nav data-gjs="navbar-menu" class="navbar-menu"><a href="#" class="navbar-menu-link">Home</a><a href="#" class="navbar-menu-link">About</a><a href="#" class="navbar-menu-link">Contact</a></nav></div></div></div><form class="form"><div class="form-group"><label class="label">Name</label><input placeholder="Type here your name" class="input"/></div><div class="form-group"><label class="label">Email</label><input type="email" placeholder="Type here your email" class="input"/></div><div class="form-group"><label class="label">Gender</label><input type="checkbox" value="M" class="checkbox"/><label class="checkbox-label">M</label><input type="checkbox" value="F" class="checkbox"/><label class="checkbox-label">F</label></div><div class="form-group"><label class="label">Message</label><textarea class="textarea"></textarea></div><div class="form-group"><button type="submit" class="button">Send</button></div></form>
');
        
        $this->html->enableSection('main');
        
        parent::add($this->html);
    }
        
    public static function onSave($param)
    {
        var_dump($param);
    }
}